## **Installing required libraries**

In [1]:
!pip install pandas

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (1.3.5)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (2022.1)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (1.21.6)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)

## **Importing required libraries**

In [2]:
import pandas as pd
import os

## **Dropping all unrequired fields to fetch necessary data for further processing (Preprocessing of fetched data).**

In [ ]:
# Data cleaning
df= pd.read_csv("../Data/Initialdataset.csv")
df2=df.drop(['ParentId','DeletionDate','OwnerDisplayName','OwnerUserId','FavoriteCount','CommunityOwnedDate','ContentLicense','ClosedDate','LastEditorUserId','LastEditorDisplayName','LastEditDate','LastActivityDate'],axis=1)
Postdf = df2.dropna().reset_index(drop=True)
Postdf

,Id,PostTypeId,AcceptedAnswerId,CreationDate,Score,ViewCount,Body,Title,Tags,AnswerCount,CommentCount
0,65567880,1,65568530.0,2021-01-04 18:27:10,0,86,<p>I want to group by a multiple fields of a c...,Collectors.groupingBy giving java.lang.ArrayIn...,<java>,1,3
1,66307249,1,66308029.0,2021-02-21 21:21:30,0,137,"<p>I am doing a simple project in java swing, ...",java.lang.UnsatisfiedLinkError in Swing,<java>,1,0
2,65864366,1,65864563.0,2021-01-23 21:04:04,-1,59,<p>I want to print a quiz to my GUI using my d...,How can I draw a string array in Java which ch...,<java>,1,0
3,66306826,1,66306909.0,2021-02-21 20:30:27,0,76,<p>I have an array of dice that are apart of a...,Java: using the values read from the user,<java>,1,2
4,65568018,1,65568715.0,2021-01-04 18:37:05,-2,75,<pre><code>&quot;ab&quot; + 'c' // String + ch...,Difference between String + char and String + ...,<java>,1,6
...,...,...,...,...,...,...,...,...,...,...,...
407,66364907,1,66365074.0,2021-02-25 08:30:42,0,387,<p>Is it possbile to give a default request ex...,how to make swagger post parameter have a defa...,<java>,2,3
408,66369417,1,66370930.0,2021-02-25 13:26:05,-1,82,<p>Small Java question regarding how to remove...,Java - Remove only the first backslash,<java>,2,5
409,66369989,1,66373141.0,2021-02-25 14:01:08,-1,47,<p>I have data something like below:</p>\n<pre...,How to read XML Response CSV Data in Java,<java>,1,1
410,66376694,1,66376991.0,2021-02-25 21:27:17,2,60,<p>I'm trying out Interfaces in java and I wan...,How to implement an interface for two classes ...,<java>,2,2
411,66378551,1,66378627.0,2021-02-26 00:40:50,1,79,<p>I'm pretty new to Java so please be lenient...,"Java - Map<String, List<Object>> iterate throu...",<java>,4,2

## **Adding respective Question ID to construct links and append to dataset.**

In [ ]:
# adding question link 
Postdf['link']= 'https://stackoverflow.com/q/'+ Postdf['Id'].astype(str)
os.makedirs('folder/subfolder', exist_ok=True)  
Postdf.to_csv('../Data/final_out.csv')